### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by sardear** [SARBook/software#1]

**Comment by PNaughton** [comment]
https://www.sdms.afrl.af.mil/ has some of it. You have to make an account

@SARBook what is `signal.mat` referring to  in ch3/range_doppler_point_target_example.ipynb

**Comment by PNaughton** [comment]
I am also unable to find the learjet data at the link above. Am I missing something?

**Comment by SARBook** [comment]
The Learjet was simulated with Lucernhammer (http://radarsoftware.com/) and provided by Walton C. Gibson.  Raw signature data is often far too large for GitHub.  signal.mat is the simulated radar return from point targets for the range Doppler example.
