### ISSUE TITLE
Error using load Unable to find file or directory 'signal.mat'.

### ISSUE THREAD

**Issue by bambang** [SARBook/software#3]
Where can I find the signal.mat file used in [range_doppler_point_target_example.mlx](https://github.com/SARBook/software/blob/main/matlab/Chapter3/range_doppler_point_target_example.mlx) ?

**Comment by SARBook** [comment]
Let me check on that one.  It may have been omitted due to a size issue.

**Comment by bambang** [comment]
any update on this issue?

**Comment by oneluckypic** [comment]
I am also looking for signal.mat. Thank you.

**Comment by RadarBook** [comment]
SDMS has moved.  

https://www.afrl.af.mil/About-Us/Fact-Sheets/Fact-Sheet-Display/Article/2331781/afrlry-compase-sensor-data-management-system/  

Also, commercial companies such as ICEYE, Umbra, and others have excellent data that can be leveraged.

**Comment by SARBook** [comment]
See comments above
