### ISSUE TITLE
Accessing data from outside US

### ISSUE THREAD

**Issue by shubhamsharma1609** [SARBook/software#4]
The data utilised in the book is of SDMS (Sensor Data Management System) which cannot be accessed outside USA. Kindly provide any way to download the data so that the utilisation of the book will be useful.

**Comment by RadarBook** [comment]
If SDMS does not allow access outside the US, then I certainly can not provide that data to you.

However, several commercial companies such as ICEYE and Umbra have excellent data.

**Comment by SARBook** [comment]
See comments above
